### ISSUE TITLE
運営管理者の追加及び全ユーザーの取引を確認したい

### ISSUE THREAD

**Issue by kabane** [match8969/cloud_funding_app#14]
## 要望
全てのユーザーの取引状態等を管理する運営管理者という概念を追加したい。
また、運営管理者ユーザーでログインを行った場合、全ユーザーの取引状況(investment)を見れるページがほしい。

## 仕様
- ユーザーが運営権限を持っているかの判定は、新たにUserテーブルにroleというカラムを追加し、その値で判断する(例えば「0が一般ユーザー」で「1が運営権限を持ったユーザー」といった具合)
※ roleカラムはenumに対応させる(enumは調べること)

- role情報の変更はブラウザ上では行えないこと(rails cからのみ変更可)とする(現状において町田さん以外運営権限を持つことはできない仕様になる)

- 運営権限を持ったユーザーが閲覧可能なページ(Controller/View)は、新たにadministerというネームスペースを設け、その中で管理する

- administer直下に全ユーザーの投資一覧を確認するためのInvestmentsControllerを設ける

**Comment by match8969** [comment]
上記要望の
>全ユーザーの取引状況(investment)を見れるページ

についてですが、取引の一覧のイメージで間違いないでしょうか?
4つのカラムをもつテーブルを表示する認識でおります。

カラム:
投資id, 商品名, ユーザー名,  投資金額

**Comment by kabane** [comment]
@match8969 
認識あっているかと！
ただし、ここで表示するinvestmentsは全ユーザーの取引情報となりますので、そこを認識していただいていれば、問題ないです。

**Comment by match8969** [comment]
@kabane 
ありがとうございます!
「ログイン中のユーザーの取引情報」ではなく、
「全ユーザーの取引情報」ですね。
クリアになりました。ありがとうございます。
