### ISSUE TITLE
メッセージ機能を追加

### ISSUE THREAD

**Issue by kabane** [match8969/cloud_funding_app#25]
## 要望
出資者が出品者(Productのオーナー)とやりとりする機能がほしい(TwitterのDMに近いイメージ)

## 要件
- FacebookやTwitterのDM機能のようにチャットのようなやりとりが行えるようにする
- メッセージはあるProductのオーナーと出資したユーザーでしかできない(出資を行ってないユーザーとはやりとりできない)
- 新規で追加するテーブルはmessage_groups(誰と誰のやりとりか)とmessages(message_groupに属するユーザーやり取り情報)
- message_groupsはusersと多対多で紐づく

## 備考
まずはここまでの情報でCacooを使用しER図を作成、テーブルの構成/カラムを考えて確認をとること。ER図に含めるのは今回の処理に関連するテーブル情報のみで良しとする。

**Comment by match8969** [comment]
@kabane 
下記にER図を作成しました。
自信が持てていないので、ご指摘箇所などぜひ
レビューのほどよろしくおねがいします。

![draft_relation_1](https://user-images.githubusercontent.com/33335788/57901514-7a17ee80-78a0-11e9-9f19-81bf2089763c.png)

**Comment by kabane** [comment]
@match8969 
まずmessage_groupsですが、中間テーブル含めてカラムの構成を考えてみてください。現状においてmessage_groupsテーブルがもつべきカラムはidのみで事足りるはずです。

messageテーブルですが、user_idはfrom_user_idというカラム名でよいかと、またusersテーブルとリレーションをする必要はないはずなので、このあたりは改めて考えてみてくださいー。

**Comment by match8969** [comment]
@kabane 
>[要件]新規で追加するテーブルはmessage_groupsとmessages (A)
>まずmessage_groupsですが、中間テーブル含めてカラムの構成を考えてみてください (B)

すいません。(A)から追加できるテーブルは2つの認識で間違い無いでしょうか?
(B)の「中間テーブル」の意味は
「中間テーブルであれば作成して良い」という意味でしょうか?

messagesテーブルでのfrom_user_idの部分はかしこまりました。

**Comment by match8969** [comment]
@kabane 
上記の追加をして良い認識であれば、下記を考えております。
ご教授いただければと思います。

![draft_relation _2](https://user-images.githubusercontent.com/33335788/57905665-34fcb800-78b2-11e9-9495-0275f276e190.png)

**Comment by kabane** [comment]
@match8969 
messagesはmessage_groupsに紐づくで良いのでは？

**Comment by match8969** [comment]
@kabane 
>messagesはmessage_groupsに紐づくで良いのでは？
失礼しました。要件に記載されている箇所でした。
修正いたしました。

![draft_relation_3](https://user-images.githubusercontent.com/33335788/57907228-bc98f580-78b7-11e9-80a4-73d3f68186c3.png)

**Comment by kabane** [comment]
@match8969 OKです！実装に入ってもらって大丈夫ですー。

**Comment by match8969** [comment]
@kabane 
ありがとうございます!!
