### ISSUE TITLE
ページ全体のリクエストスペックを書く

### ISSUE THREAD

**Issue by kabane** [match8969/cloud_funding_app#30]

**Comment by match8969** [comment]
@kabane 
一点質問なのですが、リクエストスペックの要件として、下記の認識で間違いないでしょうか?

・各controllerクラスに対応するrequest specを作成する。
(例：
controllers/products_controller.rb -> /requests/products_spec.rb
controlelrs/admin/products_controlelr.rb -> /requests/admin/products_spec.rb
)
・各rspecのファイルでテストを行うのは使用されているアクション全てがテスト対象。

**Comment by kabane** [comment]
> ・各rspecのファイルでテストを行うのは使用されているアクション全てがテスト対象。

**Comment by match8969** [comment]
@kabane 
かしこまりました。
ありがとうございます!

**Comment by match8969** [comment]
@kabane 
お手数ですが、一度イメージの確認として、 spec/requests/administer/categories_spec.rbのテストの書き方で、方向性はあってますでしょうか?
Commit:  Add category request spec #30
SHA:60520951215aecebc55ba6607e613271cb799b71

**Comment by kabane** [comment]
@match8969 上記現段階でPRを作成いただいてもよろしいでしょうか？
