### ISSUE TITLE
投資状況がレポートページを作りたい

### ISSUE THREAD

**Issue by kabane** [match8969/cloud_funding_app#32]
## 要望
どのプロダクトに誰がいくら投資したかを確認するためのページがほしい

## 要件
- 1.指定期間中に自身のProductに対し、投資を行ったユーザーの情報を一覧で出す
*期間(日付の開始・終了日のセット)を選択するためのフォームをビューに設ける
-  2.1の「ユーザーの情報」は以下の3つから構成せれる
   - 投資を行ったユーザーの氏名
   - 投資を行ったプロダクト
   - 投資額
※上記のページで表示するための情報を計算するロジックはService層に持たせる
- 3.このページのエンドポイントはAdministraotr::InvestmentsController#reportとする

参考
- Service層については、以下の記事でServiceについて説明を行っている箇所を参考にする
https://techracho.bpsinc.jp/hachi8833/2013_11_19/14738

**Comment by match8969** [comment]
質問なのですが、
>指定期間中に自身のProductに対し、投資を行ったユーザーの情報を一覧で出す
>*期間(日付の開始・終了日のセット)を選択するためのフォームをビューに設ける

の一覧で出力するページは「ログインしたユーザー」が使用できる「investment」の一覧ページ
の認識で間違いないでしょうか?
